name: CI Pipeline

on:
  push:
    branches: [main, dev]
    tags:
      - '[0-9][0-9].[0-9][0-9].[0-9][0-9]'
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install project dependencies
        run: pnpm install

      - name: Build project
        run: pnpm run build
